services:
  markcv:
    image: ghcr.io/lucanori/markcv:latest
    container_name: markcv
    ports:
      - "9876:9876"
    volumes:
      - ./data:/app/data
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: unless-stopped
    labels:
      # Enable Watchtower, remove if not needed
      - com.centurylinklabs.watchtower.enable=true